# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(766, 476)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.pageNothing = QtWidgets.QWidget()
        self.pageNothing.setObjectName("pageNothing")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.pageNothing)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelA = QtWidgets.QLabel(self.pageNothing)
        self.labelA.setTextFormat(QtCore.Qt.MarkdownText)
        self.labelA.setAlignment(QtCore.Qt.AlignCenter)
        self.labelA.setObjectName("labelA")
        self.gridLayout_2.addWidget(self.labelA, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageNothing)
        self.pageTab = QtWidgets.QWidget()
        self.pageTab.setObjectName("pageTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.pageTab)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.pageTab)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_4.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_4.setSpacing(5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.textInfo = QtWidgets.QPlainTextEdit(self.tab)
        self.textInfo.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.textInfo.setReadOnly(True)
        self.textInfo.setObjectName("textInfo")
        self.gridLayout_4.addWidget(self.textInfo, 0, 0, 1, 1)
        self.labelT1A = QtWidgets.QLabel(self.tab)
        self.labelT1A.setObjectName("labelT1A")
        self.gridLayout_4.addWidget(self.labelT1A, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageTab)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 766, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.actionLogin = QtWidgets.QAction(MainWindow)
        self.actionLogin.setObjectName("actionLogin")
        self.menu.addAction(self.actionLogin)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelA.setText(_translate("MainWindow", "**实际上, 什么都没有发生**\n"
"\n"
"\n"
"**如果你想要干什么事的话**\n"
"\n"
"\n"
"**我的建议是, 完成登录**\n"
"\n"
"---\n"
"\n"
"**HM 20210702**"))
        self.labelT1A.setText(_translate("MainWindow", "这并不是重要的部分, 因此潦草一点并无问题"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "个人信息"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.menu.setTitle(_translate("MainWindow", "菜单(&N)"))
        self.actionLogin.setText(_translate("MainWindow", "登录(&L)"))
