# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(766, 476)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.pageNothing = QtWidgets.QWidget()
        self.pageNothing.setObjectName("pageNothing")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.pageNothing)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelA = QtWidgets.QLabel(self.pageNothing)
        self.labelA.setTextFormat(QtCore.Qt.MarkdownText)
        self.labelA.setAlignment(QtCore.Qt.AlignCenter)
        self.labelA.setObjectName("labelA")
        self.gridLayout_2.addWidget(self.labelA, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageNothing)
        self.pageTab = QtWidgets.QWidget()
        self.pageTab.setObjectName("pageTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.pageTab)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.pageTab)
        self.tabWidget.setObjectName("tabWidget")
        self.tabLog = QtWidgets.QWidget()
        self.tabLog.setObjectName("tabLog")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tabLog)
        self.gridLayout_5.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_5.setSpacing(5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.textLog = QtWidgets.QPlainTextEdit(self.tabLog)
        self.textLog.setObjectName("textLog")
        self.gridLayout_5.addWidget(self.textLog, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabLog, "")
        self.tabPersonInfo = QtWidgets.QWidget()
        self.tabPersonInfo.setObjectName("tabPersonInfo")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tabPersonInfo)
        self.gridLayout_4.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_4.setSpacing(5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.textInfo = QtWidgets.QPlainTextEdit(self.tabPersonInfo)
        self.textInfo.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.textInfo.setReadOnly(True)
        self.textInfo.setObjectName("textInfo")
        self.gridLayout_4.addWidget(self.textInfo, 0, 0, 1, 1)
        self.labelT1A = QtWidgets.QLabel(self.tabPersonInfo)
        self.labelT1A.setObjectName("labelT1A")
        self.gridLayout_4.addWidget(self.labelT1A, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tabPersonInfo, "")
        self.tabSelectedCourses = QtWidgets.QWidget()
        self.tabSelectedCourses.setObjectName("tabSelectedCourses")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tabSelectedCourses)
        self.gridLayout_6.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_6.setSpacing(5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.tableSelectedCourses = QtWidgets.QTableView(self.tabSelectedCourses)
        self.tableSelectedCourses.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableSelectedCourses.setObjectName("tableSelectedCourses")
        self.gridLayout_6.addWidget(self.tableSelectedCourses, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.labelT3A = QtWidgets.QLabel(self.tabSelectedCourses)
        self.labelT3A.setObjectName("labelT3A")
        self.horizontalLayout.addWidget(self.labelT3A)
        self.comboBoxTerms = QtWidgets.QComboBox(self.tabSelectedCourses)
        self.comboBoxTerms.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBoxTerms.setObjectName("comboBoxTerms")
        self.horizontalLayout.addWidget(self.comboBoxTerms)
        self.btnQuery = QtWidgets.QPushButton(self.tabSelectedCourses)
        self.btnQuery.setObjectName("btnQuery")
        self.horizontalLayout.addWidget(self.btnQuery)
        self.gridLayout_6.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabSelectedCourses, "")
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageTab)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 766, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSet = QtWidgets.QMenu(self.menubar)
        self.menuSet.setObjectName("menuSet")
        MainWindow.setMenuBar(self.menubar)
        self.actionLogin = QtWidgets.QAction(MainWindow)
        self.actionLogin.setObjectName("actionLogin")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.menuFile.addAction(self.actionLogin)
        self.menuSet.addAction(self.actionSettings)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSet.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelA.setText(_translate("MainWindow", "**实际上, 什么都没有发生**\n"
"\n"
"\n"
"**如果你想要干什么事的话**\n"
"\n"
"\n"
"**我的建议是, 完成登录**\n"
"\n"
"---\n"
"\n"
"**HM 20210702**"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabLog), _translate("MainWindow", "输出信息"))
        self.labelT1A.setText(_translate("MainWindow", "这并不是重要的部分, 因此潦草一点并无问题"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPersonInfo), _translate("MainWindow", "个人信息"))
        self.labelT3A.setText(_translate("MainWindow", "学期"))
        self.btnQuery.setText(_translate("MainWindow", "查询"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSelectedCourses), _translate("MainWindow", "已选课程"))
        self.menuFile.setTitle(_translate("MainWindow", "菜单(&N)"))
        self.menuSet.setTitle(_translate("MainWindow", "设置(&S)"))
        self.actionLogin.setText(_translate("MainWindow", "登录(&L)"))
        self.actionSettings.setText(_translate("MainWindow", "设置"))
